<!-- Main Content -->
<div id="content">

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Ajouter un article</h1>
        </div>
        <div class="d-inline-block">
            <?php
            // Si data n'est pas vide sur cette page, c'est qu'il y'a un message à afficher
            if (isset($data)) {
                foreach ($data as $key => $message) {
                    echo $message;
                }
            }
            ?>
        </div>

        <!-- Area Chart -->

        <form class="row" action="" method="post">
            <div class="col-10 card shadow mb-4 p-0">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <input type="text" name="title" class="p-2 col-6" placeholder="Titre de l'article">
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <input type="text" name="thumbnail" placeholder="nom de de l'image de la vignette (ex: nom.jpg)" class="col-6 p-2 mb-4">
                    <textarea name="content" id="" rows="30" class="w-100 p-2" placeholder="Contenu de l'article (html accepté)"></textarea>
                    <p>Catégories</p>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="categories[]" value="1" id="flexCheckDefault">
                        <label class="form-check-label" for="flexCheckDefault">
                            Default checkbox
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="categories[]" value="2" id="flexCheckChecked" checked>
                        <label class="form-check-label" for="flexCheckChecked">
                            Checked checkbox
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-2 ">
                <!-- on n'oublie pas le name sur le bouton submit pour identifier le formulaire dans le AdminController  -->
                <input type="submit" class="btn btn-sm btn-primary shadow-sm position-fixed" name="addPostForm" value="Créer l'article">
            </div>
        </form>


    </div>
    <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->