<!-- Page Header-->
<header class="masthead" style="background-image: url('<?= $base_uri[0]; ?>/public/assets/front/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">   
            <?php foreach($data as $post): ?>
            <!-- Post preview-->
            <div class="post-preview">
                <a href="<?= $base_uri[0]; ?>/public/post/<?= $post->getId(); ?>">
                    <img src="assets/front/img/<?=$post->getImg();?>" alt="" class="img-fluid">
                    <h2 class="post-title"><?= $post->getTitle(); ?></h2>
                    <p><?= $post->getContent(); ?></p>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="">Start Bootstrap</a>
                    <?= $post->getDate(); ?>
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <?php endforeach; ?>            
            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
        </div>
    </div>
</main>

