<!-- Page Header-->

<header class="masthead" style="background-image: url('<?= $base_uri[0]; ?>/public/assets/front/img/<?=$data->getImg();?>">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-10 col-xl-10">
                <div class="site-heading">
                 <h1><?= $data->getTitle(); ?></h1>                    
                </div>
            </div>
        </div>
    </div>
</header>
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">                                
                <small><?= $data->getDate(); ?></small>
                <p><?= $data->getContent(); ?></p>
                <p>
                    Placeholder text by
                    <a href="http://spaceipsum.com/">Space Ipsum</a>
                    &middot; Images by
                    <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>
                </p>
            </div>
        </div>
    </div>
</article>