<header class="masthead" style="background-image: url('<?= $base_uri[0]; ?>/public/assets/front/img/contact-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Inscription</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<main class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <?php if (isset($data)) : ?>
                            <?php if (!empty($data['errors'])) : ?>
                                <?php foreach ($data['errors'] as $error) : ?>
                                    <?= $error; ?>
                                <?php endforeach; ?>                       
                            <?php elseif (!empty($data['success'])) : ?>
                                <?= $data['success']; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                        </div>
                        <form class="user" action="" method="post">
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">                                    
                                    <input type="text" name="name" class="form-control form-control-user" id="exampleFirstName" placeholder="Name" value="<?php if(!empty($_POST['name'])){echo $_POST['name'];} ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="email" name="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address" value="<?php if(!empty($_POST['email'])){echo $_POST['email'];} ?>">
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input type="password" name="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                                </div>
                            </div>
                            <input class="btn btn-primary" type="submit" value="Envoyer">
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="forgot-password.html">Forgot Password?</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="login.html">Already have an account? Login!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>